export const ARCHIVE_ITEMS = [
  {
    id: "01",
    name: "Noa",
    series: "Series 01",
    year: "2026",
    type: "Standard",
    image: "/images/texture-01.svg",
  },
  {
    id: "02",
    name: "Eos",
    series: "Series 01",
    year: "2026",
    type: "Limited",
    image: "/images/texture-02.svg",
  },
  {
    id: "03",
    name: "Kaia",
    series: "Series 02",
    year: "2027",
    type: "Prototype",
    image: "/images/texture-03.svg",
  },
  {
    id: "04",
    name: "Lune",
    series: "Collab",
    year: "2025",
    type: "One-off",
    image: "/images/texture-04.svg",
  },
  {
    id: "05",
    name: "Sol",
    series: "Concept",
    year: "2026",
    type: "Render",
    image: "/images/texture-05.svg",
  },
  {
    id: "06",
    name: "Iris",
    series: "One-off",
    year: "2024",
    type: "Sold Out",
    image: "/images/texture-06.svg",
  },
];
